# -*- coding: utf-8 -*-
"""Car_Code

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DsGEI_g2d8vv49mCUSaO273YxtzyM6-5
"""

!pip install evdev #We need to install evdev first as it does not come with the base python
!pip install RPi.GPIO

import evdev #Allows us to use a xbox coontroller.
#We will ned evtest to test the functions of our controller once connected to the PI.
import numpy as np
import time

try:
    import RPi.GPIO as GPIO #This will allow us to confirgure certain pins on the raspberry pi for our applications.
    print("RPi.GPIO imported successfully. Running on a Raspberry Pi.")
except RuntimeError:
    print("RPi.GPIO import failed. Running in a non-Raspberry Pi environment (e.g., Colab). Using dummy GPIO.")

    class DummyGPIO:
        BCM = "BOARD" # A placeholder for the mode, can be 'BCM' or 'BOARD'
        OUT = "OUT" # A placeholder for output direction

        def setmode(self, mode):
            print(f"Dummy GPIO: setmode({mode})")

        def setup(self, pin, direction):
            print(f"Dummy GPIO: setup(pin={pin}, direction={direction})")

        def output(self, pin, value):
            print(f"Dummy GPIO: output(pin={pin}, value={value})")

        def cleanup(self):
            print("Dummy GPIO: cleanup()")

        class DummyPWM:
            def __init__(self, pin, frequency):
                self.pin = pin
                self.frequency = frequency
                print(f"Dummy PWM: Initialized for pin {pin} at {frequency}Hz")

            def start(self, duty_cycle):
                print(f"Dummy PWM: Started with duty cycle {duty_cycle}%")

            def ChangeDutyCycle(self, duty_cycle):
                print(f"Dummy PWM: Changed duty cycle to {duty_cycle}%")

            def stop(self):
                print("Dummy PWM: Stopped")

        def PWM(self, pin, frequency):
            return self.DummyPWM(pin, frequency)

    GPIO = DummyGPIO()
#This code allows us to import GPIO. TRaditionally, collab which I am doing my coding on. does not allow
#you to import GPIO. it will give you a name error. So this code allows us to bypass this issue and continue
#to use collab and code.

#Here will be where we begin to configure the pins of a raspberry pi to our DC motors.
GPIO.setmode(GPIO.BCM)

def forward(speed):
  print(f"going fowrad at speed{speed}%")
  GPIO.output(31, False)
  pinOneMotor_pwm.ChangeDutyCycle(speed)
#More code to come, just going to the gym.
