# -*- coding: utf-8 -*-
"""Rexy_FinalCode

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KEVUx8LyKbyTc4xJtbvJsGLsVvvLxK-I
"""

open("/home/squea/started.txt", "W").write("Started")

import evdev
from evdev import InputDevice, list_devices
import numpy as np
import time
import RPi.GPIO as GPIO

#Setting the pins----------------------------------------------------------------
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)

#Pin Assignments:
DRIVE_AIN1 = 23
DRIVE_AIN2 = 24
DRIVE_PWMA = 18

STEER_BIN1 = 17
STEER_BIN2 = 27
STEER_PWMB = 13

STBY = 22

#Setting up the GPIO pins:
GPIO.setup(DRIVE_AIN1, GPIO.OUT)
GPIO.setup(DRIVE_AIN2, GPIO.OUT)
GPIO.setup(DRIVE_PWMA, GPIO.OUT)

GPIO.setup(STEER_BIN1, GPIO.OUT)
GPIO.setup(STEER_BIN2, GPIO.OUT)
GPIO.setup(STTER_PWMB, GPIO.OUT)

GPIO.setup(STBY, GPIO.OUT)
GPIO.output(STBY, HIGH)

driveMotor_pwm = GPIO.PWM(DRIVE_PWMA, 1000)
driveMotor_pwm.start(0)
stterMotor_pwm = GPIO.PWM(STEER_PWMB, 1000)
steerMotor_pwm.start(0)

#Finding the Device------------------------------------------------------------
def find_xbox_controller():
  devices = [InputDevice(dev) for dev in list_devices()]
  for dev in devices:
    if 'Xbox' in dev.name or 'X-box' in dev.name:
      print(f"found xbox controller at: {dev.path}")
      return dev.path
  print("no xbox controller found")
  return None

  controller_path = find_xbox_controller()

  if controller_path:
    device = InputDevice(controller_path)
    print(f"using controller: {device}")
  else:
    exit("no xbox controller found")

#Movements functions (reference to motor controller truth table)------------------------------------------------
def forward(speed):
  print(f"going forward at speed{speed}%")
  GPIO.output(DRIVE_AIN1, HIGH)
  GPIO.output(DRIVE_AIN2, LOW)
  driveMotor_pwm.ChangeDutyCycle(speed)

def backward(speed):
  print(f"going backward at speed{speed}%")
  GPIO.output(DRIVE_AIN1, LOW)
  GPIO.output(DRIVE_AIN2, HIGH)
  driveMotor_pwm(speed)

def steer_left(speed):
  print(f"turning left at speed{speed}%")
  GPIO.output(STEER_BIN1, HIGH)
  GPIO.output(STEER_BIN2, LOW)
  steerMotor_pwm.ChangeDutyCycle(speed)

def steer_right(speed):
  print(f"turning right at speed{speed}%")
  GPIO.output(STEER_BIN1, LOW)
  GPIO.output(STEER_BIN2, HIGH)
  steerMotor_pwm.ChangeDutyCycle(speed)

def stop_steer(speed):
  print(f"stopping steering")
  GPIO.output(STEER_BIN1, LOW)
  GPIO.output(STEER_BIN2, LOW)
  steerMotor_pwm.ChangeDutyCycle(0)

def stop_drive(speed):
  print(f"stopping drive")
  GPIO.output(DRIVE_AIN1, LOW)
  GPIO.output(DRIVE_AIN2, LOW)
  driveMotor_pwm.ChangeDutyCycle(0)

#Controller Inputs--------------------------------------------------------------------------
def controller_value(value, in_min, in_max, out_min, out_max):
  return np.interp(value, [in_min,in_max],[out_min, out_max])

#Steering function (for left and right controller and the upper left joystick on the Xbox controller)------------------------------
def handle_steering(x_value):
  deadzone = 0.15
  print(f"[STEER] handle_steering called, x_value = {x_value:.3f}")
  if abs(x_value)<deadzone:
    print("[STEER] stopping steering -> steer_stop()")
    stop_steer(0)
    return

  speed = controller_value(abs(x_value), 0, 1, 0, 100)

  if x_value<0:
    print("[STEER] turning left -> steer_left()")
    steer_left(speed/4)
  elif x_value>0:
    print("[STEER] turning right -> steer_right()")
    steer_right(speed/4)

#Forward and Backwards movents with the left and right trigger conrtols on the controller-------------------------------------------
try:
  if isinstance(device, evdev.InputDevice):
    for event in device.read_loop():
      if event.type == evdev.ecodes.EV_ABS:
        #Right trigger:
        if event.code == evdev.ecodes.ABS_GAS:
          speed = round(controller_value(event.value, 0, 1023, 0, 100))
          print(f"right trigger:{event.value}")
          forward(speed)
        elif event.code == evdev.ecodes.ABS_BRAKE:
          speed = round(controller_value(event.value, 0, 1023, 0, 100))
          print(f"left trigger:{event.value}")
          backward(speed)
        elif event.code == evdev.ecodes.ABS_X:
          x_raw = event.value
          x_norm = controller_value(x_raw, 0, 65535, -1, 1)
          print(f"steering raw: {x_raw}, norm: {x_norm:.2f}")
          handle_steering(x_norm)
  else:
    print("skipping controller event loop")
except KeyboardInterrupt:
  pass
finally:
  GPIO.cleanup()

